### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by hcgreier** [i-net-software/dokuwiki-plugin-popupviewer#31]
Hi,

installed it, but I get 2 errors after reloading the wiki:

[urlpath]\lib\plugins\popupviewer\syntax\viewer.php on line 45
[urlpath]\lib\plugins\popupviewer\syntax\viewer.php on line 62

When reloading the page, the errors go away, but no external site is loaded into the popup.
This was tested on a localhost Apache with PHP v8.2, wiki with "Jack Jackrum".

Must the wiki run on an online server for the popup to work?

Thx,
hc

**Comment by Jurik-Phys** [comment]
I have the same error. Dokuwiki log:

```
2025-05-27 16:13:01E_WARNING: Undefined variable $ID/opt/www/wiki/lib/plugins/popupviewer/syntax/viewer.php(62)
    #0 /opt/www/wiki/lib/plugins/popupviewer/syntax/viewer.php(62): dokuwiki\ErrorHandler::errorHandler()
    #1 /opt/www/wiki/inc/parser/handler.php(298): syntax_plugin_popupviewer_viewer->handle()
    #2 /opt/www/wiki/inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin()
    #3 /opt/www/wiki/inc/Parsing/Lexer/Lexer.php(196): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
    #4 /opt/www/wiki/inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
    #5 /opt/www/wiki/inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse()
    #6 /opt/www/wiki/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
    #7 /opt/www/wiki/inc/Ui/PageView.php(56): p_get_instructions()
    #8 /opt/www/wiki/inc/Action/Preview.php(32): dokuwiki\Ui\PageView->show()
    #9 /opt/www/wiki/inc/template.php(120): dokuwiki\Action\Preview->tplContent()
    #10 [internal function]: tpl_content_core()
    #11 /opt/www/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #12 /opt/www/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #13 /opt/www/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #14 /opt/www/wiki/lib/tpl/dokuwiki-my/main.php(60): tpl_content()
    #15 /opt/www/wiki/inc/actions.php(30): include('...')
    #16 /opt/www/wiki/doku.php(131): act_dispatch()
    #17 {main}
2025-05-27 16:13:01E_WARNING: Undefined array key 1/opt/www/wiki/lib/plugins/popupviewer/syntax/viewer.php(45)
    #0 /opt/www/wiki/lib/plugins/popupviewer/syntax/viewer.php(45): dokuwiki\ErrorHandler::errorHandler()
    #1 /opt/www/wiki/inc/parser/handler.php(298): syntax_plugin_popupviewer_viewer->handle()
    #2 /opt/www/wiki/inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin()
    #3 /opt/www/wiki/inc/Parsing/Lexer/Lexer.php(196): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
    #4 /opt/www/wiki/inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
    #5 /opt/www/wiki/inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse()
    #6 /opt/www/wiki/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
    #7 /opt/www/wiki/inc/Ui/PageView.php(56): p_get_instructions()
    #8 /opt/www/wiki/inc/Action/Preview.php(32): dokuwiki\Ui\PageView->show()
    #9 /opt/www/wiki/inc/template.php(120): dokuwiki\Action\Preview->tplContent()
    #10 [internal function]: tpl_content_core()
    #11 /opt/www/wiki/inc/Extension/Event.php(134): call_user_func_array()
    #12 /opt/www/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #13 /opt/www/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
    #14 /opt/www/wiki/lib/tpl/dokuwiki-my/main.php(60): tpl_content()
    #15 /opt/www/wiki/inc/actions.php(30): include('...')
    #16 /opt/www/wiki/doku.php(131): act_dispatch()
    #17 {main}
```
